"""Compute a standardized anomaly (SPI-like) drought index for a timeseries.

Generated by the ESMFlow onboarding agent.

User code:  examples.user_code.drought_indices.compute_standardized_anomaly_index
Subagent:   diagnostics

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.

Onboarding notes:
  - output 'index_file': assumed csv from its name; change to netcdf/png if the function produces those
  - subagent defaulted to 'diagnostics'; reassign if this capability belongs to another category (data_discovery, extraction, diagnostics, water_cycle, visualization) or a new one
"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = 'examples.user_code.drought_indices'
USER_FUNCTION = 'compute_standardized_anomaly_index'

SPEC = ToolSpec(
    name='compute_standardized_anomaly_index',
    description='Compute a standardized anomaly (SPI-like) drought index for a timeseries.',
    inputs={
        'input_file': Param(type='path', required=True, description='CSV timeseries with a time column and at least one numeric column.'),
        'value_column': Param(type='str', description='Column to analyze. Defaults to the first numeric column.'),
        'accumulation_months': Param(type='int', default=3, description='Rolling accumulation window in months.'),
        'drought_threshold': Param(type='float', default=-1.0, description='Index value below which a month counts as drought.'),
    },
    outputs={
        'index_file': {'type': 'csv'},
        'n_drought_months': {'type': 'int'},
        'min_index': {'type': 'float'},
    },
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
