"""Summarize snow season timing and magnitude per water year.

Generated by the ESMFlow onboarding agent.

User code:  examples.user_code.snow_metrics.compute_snow_season_metrics
Subagent:   diagnostics

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.

Onboarding notes:
  - output 'metrics_file': assumed csv from its name; change to netcdf/png if the function produces those
  - subagent defaulted to 'diagnostics'; reassign if this capability belongs to another category (data_discovery, extraction, diagnostics, water_cycle, visualization) or a new one
"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = 'examples.user_code.snow_metrics'
USER_FUNCTION = 'compute_snow_season_metrics'

SPEC = ToolSpec(
    name='compute_snow_season_metrics',
    description='Summarize snow season timing and magnitude per water year.',
    inputs={
        'input_file': Param(type='path', required=True, description='CSV timeseries containing a time column and an SWE column.'),
        'swe_column': Param(type='str', description="SWE column name. Defaults to a column containing 'swe'."),
        'swe_threshold': Param(type='float', default=0.005, description='SWE value (same units as input) defining snow presence.'),
        'water_year_start_month': Param(type='int', default=10, description='Month that starts the water year (1-12).'),
    },
    outputs={
        'metrics_file': {'type': 'csv'},
        'n_water_years': {'type': 'int'},
        'mean_snow_duration_days': {'type': 'float'},
    },
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
