"""Compute high- and low-flow exceedance thresholds from a streamflow CSV.

Generated by the ESMFlow onboarding agent.

User code:  examples.user_code.flow_exceedance.compute_flow_exceedance_thresholds
Subagent:   diagnostics

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.
"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = 'examples.user_code.flow_exceedance'
USER_FUNCTION = 'compute_flow_exceedance_thresholds'

SPEC = ToolSpec(
    name='compute_flow_exceedance_thresholds',
    description='Compute high- and low-flow exceedance thresholds from a streamflow CSV.',
    inputs={
        'input_file': Param(type='path', required=True, description='CSV timeseries with a time column and a streamflow column.'),
        'flow_column': Param(type='str', description='Streamflow column name. Defaults to the first numeric column.'),
        'low_flow_percentile': Param(type='float', default=95.0, description='Exceedance percentile defining low flow (0-100).'),
        'high_flow_percentile': Param(type='float', default=5.0, description='Exceedance percentile defining high flow (0-100).'),
    },
    outputs={
        'exceedance_file': {'type': 'csv'},
        'high_flow_threshold': {'type': 'float'},
        'low_flow_threshold': {'type': 'float'},
        'flashiness_ratio': {'type': 'float'},
    },
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
