"""Fit a per-gridcell least-squares linear trend to a gridded field.

Generated by the ESMFlow onboarding agent.

User code:  examples.user_code.grid_trends.compute_gridded_trend
Subagent:   diagnostics

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.

Onboarding notes:
  - subagent defaulted to 'diagnostics'; reassign if this capability belongs to another category (data_discovery, extraction, diagnostics, water_cycle, visualization) or a new one
"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = 'examples.user_code.grid_trends'
USER_FUNCTION = 'compute_gridded_trend'

SPEC = ToolSpec(
    name='compute_gridded_trend',
    description='Fit a per-gridcell least-squares linear trend to a gridded field.',
    inputs={
        'input_file': Param(type='path', required=True, description='NetCDF file containing a time-varying gridded variable.'),
        'variable': Param(type='str', description='Variable to analyze. Defaults to the first 3-D time variable.'),
        'per_decade': Param(type='bool', default=True, description='Report the slope per decade instead of per year.'),
        'min_valid_fraction': Param(type='float', default=0.6, description='Minimum fraction of finite timesteps required per cell.'),
    },
    outputs={
        'output_file': {'type': 'netcdf', 'description': 'An xarray Dataset with ``trend``, ``intercept``, ``valid_fraction`` and ``time_mean`` variables.'},
    },
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
