"""Render ESMFlow tool adapters from confirmed capability drafts.

The generated file is a completely normal ESMFlow tool: a module-level
``SPEC = ToolSpec(...)`` plus a ``run(config)`` decorated with
``@esmflow_tool(SPEC)``.  ``tools/generate_catalog.py`` therefore picks it up
with no special-casing, and ``common/workflow_runner.py`` loads it the same way
it loads every hand-written tool.

Everything domain-specific lives in the user's own module; the adapter only
forwards arguments and turns whatever comes back into declared artifacts.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from onboarding.models import CapabilityDraft

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_ROOT = REPO_ROOT / "tools"

GENERATED_MARKER = "Generated by the ESMFlow onboarding agent."


class ScaffoldError(RuntimeError):
    """Raised when a draft is not complete enough to render an adapter."""


def _py_repr(value: object) -> str:
    """Render a default value as source text."""

    return repr(value)


def validate_draft(draft: CapabilityDraft) -> List[str]:
    """Return a list of blocking problems with ``draft`` (empty means OK)."""

    problems: List[str] = []
    if not draft.tool_name or not draft.tool_name.isidentifier():
        problems.append(
            f"tool_name {draft.tool_name!r} must be a valid Python identifier"
        )
    if not draft.category or not draft.category.isidentifier():
        problems.append(
            f"category {draft.category!r} must be a single valid identifier"
        )
    if not draft.description.strip():
        problems.append("description is empty; the planner relies on it to pick tools")
    if not draft.source_module or not draft.source_function:
        problems.append("source_module and source_function are both required")
    if not draft.outputs:
        problems.append("at least one output must be declared")
    seen: set[str] = set()
    for param in draft.inputs:
        if not param.name.isidentifier():
            problems.append(f"input name {param.name!r} is not a valid identifier")
        if param.name in seen:
            problems.append(f"duplicate input name {param.name!r}")
        seen.add(param.name)
        if param.name == "output_dir":
            problems.append(
                "'output_dir' is injected by @esmflow_tool and must not be declared"
            )
    out_seen: set[str] = set()
    for output in draft.outputs:
        if output.name in out_seen:
            problems.append(f"duplicate output name {output.name!r}")
        out_seen.add(output.name)
    return problems


def _render_inputs(draft: CapabilityDraft) -> str:
    if not draft.inputs:
        return "    inputs={},"
    lines = ["    inputs={"]
    for param in draft.inputs:
        parts = [f"type={param.type!r}"]
        if param.required:
            parts.append("required=True")
        if param.default is not None:
            parts.append(f"default={_py_repr(param.default)}")
        if param.description:
            parts.append(f"description={param.description!r}")
        lines.append(f"        {param.name!r}: Param({', '.join(parts)}),")
    lines.append("    },")
    return "\n".join(lines)


def _render_outputs(draft: CapabilityDraft) -> str:
    """Render outputs in the repo's canonical ``{'type': ..., 'description': ...}``
    form, which is what ``@esmflow_tool`` and the generated catalog both expect."""

    lines = ["    outputs={"]
    for output in draft.outputs:
        parts = [f"'type': {output.type!r}"]
        if output.description:
            parts.append(f"'description': {output.description!r}")
        lines.append(f"        {output.name!r}: {{{', '.join(parts)}}},")
    lines.append("    },")
    return "\n".join(lines)


def render_adapter(draft: CapabilityDraft) -> str:
    """Return the full source text of the adapter module for ``draft``."""

    problems = validate_draft(draft)
    if problems:
        raise ScaffoldError(
            "cannot render adapter for "
            f"{draft.tool_name!r}:\n  - " + "\n  - ".join(problems)
        )

    notes = ""
    if draft.notes:
        note_lines = "\n".join(f"  - {note}" for note in draft.notes)
        notes = f"\nOnboarding notes:\n{note_lines}\n"

    return f'''"""{draft.description}

{GENERATED_MARKER}

User code:  {draft.source_module}.{draft.source_function}
Subagent:   {draft.subagent}

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.
{notes}"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = {draft.source_module!r}
USER_FUNCTION = {draft.source_function!r}

SPEC = ToolSpec(
    name={draft.tool_name!r},
    description={draft.description!r},
{_render_inputs(draft)}
{_render_outputs(draft)}
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
'''


def adapter_path_for(draft: CapabilityDraft, tools_root: Optional[Path] = None) -> Path:
    """Absolute path of the adapter file implied by ``draft``."""

    root = tools_root or TOOLS_ROOT
    return root / draft.category / f"{draft.tool_name}.py"


def write_adapter(
    draft: CapabilityDraft,
    tools_root: Optional[Path] = None,
    overwrite: bool = False,
) -> Path:
    """Render and write the adapter for ``draft``; returns the file path."""

    path = adapter_path_for(draft, tools_root)
    if path.exists():
        if not overwrite:
            raise ScaffoldError(
                f"{path} already exists; pass overwrite=True to replace it"
            )
        if GENERATED_MARKER not in path.read_text():
            raise ScaffoldError(
                f"refusing to overwrite {path}: it is not an onboarding-generated adapter"
            )
    source = render_adapter(draft)
    path.parent.mkdir(parents=True, exist_ok=True)
    init_file = path.parent / "__init__.py"
    if not init_file.exists():
        init_file.write_text(f'"""ESMFlow {draft.category} tools."""\n')
    path.write_text(source)
    return path


def remove_adapter(
    tool_name: str, category: str, tools_root: Optional[Path] = None
) -> Optional[Path]:
    """Delete a generated adapter if it exists; returns the removed path."""

    root = tools_root or TOOLS_ROOT
    path = root / category / f"{tool_name}.py"
    if not path.exists():
        return None
    if GENERATED_MARKER not in path.read_text():
        raise ScaffoldError(
            f"refusing to delete {path}: it is not an onboarding-generated adapter"
        )
    path.unlink()
    return path


def relative_adapter_path(path: Path) -> str:
    """Repo-relative POSIX path, suitable for storing in the registry."""

    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


#: Output types the runner materializes as files on disk, and their extensions.
#: Mirrors ``tools/core/adapters.FILE_OUTPUT_TYPES`` without importing it.
FILE_OUTPUT_SUFFIXES = {"csv": ".csv", "png": ".png", "netcdf": ".nc"}


def render_workflow_snippet(draft: CapabilityDraft, step_id: Optional[str] = None) -> str:
    """A copy-pasteable workflow step demonstrating the new capability.

    Follows the runner's conventions: ``outputs:`` maps an output key to the
    *filename* it should be renamed to inside ``settings.output_dir``, and later
    steps consume it with a dotted reference, ``${<step_id>.outputs.<key>}``.
    Only file-valued outputs belong in ``outputs:``; scalars stay in the step
    result and are not written to disk.
    """

    sid = step_id or f"{draft.tool_name}_step"
    lines = [
        f"- id: {sid}",
        f"  type: {draft.subagent}",
        f"  tool: {draft.tool_name}",
        "  params:",
    ]
    params: Dict[str, str] = {}
    for param in draft.inputs:
        if param.required or param.default is None:
            params[param.name] = "<fill me>" if param.type == "path" else "<value>"
    if not params:
        lines.append("    {}")
    else:
        for name, placeholder in params.items():
            lines.append(f"    {name}: {placeholder}")

    file_outputs = [
        (output.name, FILE_OUTPUT_SUFFIXES[output.type])
        for output in draft.outputs
        if output.type in FILE_OUTPUT_SUFFIXES
    ]
    if file_outputs:
        lines.append("  outputs:")
        for name, suffix in file_outputs:
            lines.append(f"    {name}: {sid}_{name}{suffix}")
        first_name = file_outputs[0][0]
        lines.append(f"# Reference this from a later step as ${{{sid}.outputs.{first_name}}}")
    return "\n".join(lines)
