"""Render a year (rows) by month (columns) heatmap of a timeseries.

Generated by the ESMFlow onboarding agent.

User code:  examples.user_code.heatmap.plot_month_year_heatmap
Subagent:   visualization

Edit the SPEC below if the parameter names, types or descriptions need to
change; the science itself lives in the user module and is not duplicated here.
"""

import sys
from pathlib import Path

# Same import convention as the hand-written tools: `tools/` goes on sys.path so
# `core.base` resolves to the single module instance whose TOOL_REGISTRY
# tools/generate_catalog.py reads.
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.adapters import call_user_function, materialize_result
from core.base import Param, ToolSpec, esmflow_tool

USER_MODULE = 'examples.user_code.heatmap'
USER_FUNCTION = 'plot_month_year_heatmap'

SPEC = ToolSpec(
    name='plot_month_year_heatmap',
    description='Render a year (rows) by month (columns) heatmap of a timeseries.',
    inputs={
        'input_file': Param(type='path', required=True, description='CSV timeseries with a time column and a numeric value column.'),
        'value_column': Param(type='str', description='Column to plot. Defaults to the first numeric column.'),
        'title': Param(type='str', default='Month-by-year heatmap', description='Figure title.'),
        'colormap': Param(type='str', default='viridis', description='Matplotlib colormap name.'),
        'aggregation': Param(type='str', default='mean', description="How to aggregate multiple values per month ('mean', 'sum', 'max', 'min')."),
    },
    outputs={
        'plot_file': {'type': 'png', 'description': 'A matplotlib Figure containing the heatmap.'},
    },
)


@esmflow_tool(SPEC)
def run(config: dict) -> dict:
    """Call the user function and materialize its return value as artifacts."""

    result = call_user_function(USER_MODULE, USER_FUNCTION, SPEC, config)
    return materialize_result(SPEC, result, config)
